[package]
name = "syntax"
version = "0.1.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
lalrpop-util = "0.16.3"
regex = "1.1.0"

[build-dependencies]
lalrpop = "0.16.3"
